title: Dorian Bauschke # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I am a data-driven analyst with a degree in economics and data science who is communicative and adaptable. I am currently pursuing a M.Sc. in Data Science at UPC Barcelona but I am looking to reorient myself into a more business related position that allows me to use my strengths in data analysis in a more applied context. I have gained work experience in Data Analysis in multiple contexts listed below and work with Excel, SQL, Tableau and R. My portfolio: bit.ly/DB_PF
  <br><br>
  <a href="https://www.linkedin.com/in/averyjsmith/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
