title: Dorian Bauschke # your name (or website title) here
logo: "/images/Professional Photo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I am a data-driven analyst with a degree in economics and data science who is 
 communicative and adaptable. I have gained work experience in Data Analysis in multiple contexts listed below and worked with Excel, SQL, Tableau and R.
 <br>
 
 
  <a href="https://www.linkedin.com/in/dorian-bauschke/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
